spring:
  application:
    name: motorcardgame-app

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:motorcardgame}
    username: ${DB_USER:motorcardgame}
    password: ${DB_PASSWORD:motorcardgame}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
